source 'https://github.com/brtterme/testSpec.git'
use_frameworks!

platform :ios, '10.0'

target 'TwoLib_Example' do
  pod 'TwoLib'
  pod 'TestLib'

  target 'TwoLib_Tests' do
    inherit! :search_paths

    
  end
end
